### ISSUE TITLE
explain how to migrate from v1 to v2

### ISSUE THREAD

**Issue by ammario** [coder/docs#1075]
We should make it explicit that the doc is incomplete and that they should reach out if they need further clarity.

**Comment by sharkymark** [comment]
sampling of topics to document tasks (even manual):

control plane
users
dev URLs
templates
configure scripts (if images reused)

data plane
/home/coder directories

**Comment by sharkymark** [comment]
@ericpaulsen -- @bpmct and I will be including you on fleshing these out in the near future.

**Comment by bpmct** [comment]
I created an internal outline, we'll discuss there first and then get to the PR
