### ISSUE TITLE
'configured access URL' link in docs 404s

### ISSUE THREAD

**Issue by misskniss** [coder/docs#1088]
## Problem

The link to the 'configured access URL' page in the Quick Start Guide gets a 404. 
![404 for Configured Access URL docs link](https://user-images.githubusercontent.com/2394436/185488418-04e7a42b-67f9-42a1-90f3-6d4d18c50bed.png)
![Doh](https://user-images.githubusercontent.com/2394436/185488569-332d8782-bb9f-4fea-85c4-7f5e1c2ca64d.png)

## Definition of Done
Clicking this link properly loads the page for URL access for users.

**Comment by ericpaulsen** [comment]
@misskniss ah good catch - I believe this belongs in `coder/coder` though!

**Comment by bpmct** [comment]
closed as completed by coder/coder#3564
