### ISSUE TITLE
[Doc] Contributing documentation

### ISSUE THREAD

**Issue by greyscaled** [coder/docs#225]
Add documentation on how to develop `cdr/docs`. Particularly, the following are needed:

- requirements (coder environment!)
- scripts and how to use them / what they're for
- where files live and what their purposes are

**Comment by jawnsy** [comment]
There's [some info in the docs](https://coder.com/docs/feedback) themselves, but it would be nice to have it transformed into an issue template or something?

**Comment by vapurrmaid** [comment]
@jawnsy I left the issue blank by accident so I'll update the description --> intention here was how to use the development scripts and the requirements `yarn`, `node` etc
